<a href="https://colab.research.google.com/github/czokw1/ml-bootcamp/blob/main/supervised/02_regression/01_linear_regression_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [1]:
import numpy as np

Getting data

In [2]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

print(f'Lata pracy:{X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczna próbek: {m}')

Lata pracy:[1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczna próbek: 6


In [5]:
X1 = X1.reshape(m,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [7]:
bias = np.ones((m,1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [9]:
X = np.append(bias,X1,axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [10]:
np.dot(X.T,X)

array([[ 6., 21.],
       [21., 91.]])

In [11]:
L =np.linalg.inv(np.dot(X.T,X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [13]:
P = np.dot(X.T,Y)
P

array([21750., 80500.])

In [14]:
np.dot(L,P)

array([2750.,  250.])

Y = 2750 + 250X1

In [15]:
from os import register_at_fork
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1,Y)

print(regression.intercept_)
print(regression.coef_[0])

2750.0
250.0
